sudo: required

language: bash
services: docker

env:
  matrix:
  - RUNTIME=python2.7 VARIANT=build
  - RUNTIME=python3.6 VARIANT=build
  - RUNTIME=nodejs4.4 VARIANT=build
  - RUNTIME=nodejs6.10.3 VARIANT=build
  - RUNTIME=nodejs8 VARIANT=build
  - RUNTIME=java8 VARIANT=build

  global:
  - REPO=aliyunfc
  - secure: "iDybJtIk4DuYBKkLxAumbXLruBSRR3LY9QNJ8neGkKd9DHU3+4TP6sYimsXtT5PVx/Jx3F7jb+t0Q4r6xx5bxGC7hKnzDjV1uH6QxvqgkOcPTLudCwo/ckZIpwG2rNTtLNycyCtrJhnwVeOU3JT+BTXBz5OMge/FT43+EiiD9AEw0+tzTx2Z7WReSsg9QXQpOST9TcKq4vK/mqHtRtlvrb7ayhGve+lP6zDxmRHmXLwyQ+60G348Li4xT7/CHoba7BdmKsflo2QIvLzQ9yBIk3yPmLdDLyacxAAqpdJSfS0Wce+FPf17Gi2O1nMyWMQu+mZdPX96g5ehIZRnIKQ3se1DhAE/B0DBMcCF452EnaEMRIGuCcNNE34sW3i58l3EBw0xbiM3iHHPXtuCIRExvprkq8zipTt6oxXecwO+9fJIz0NDZ56jQzj1O34HiUXCII1MHzCOKCyzqdc4I1qy9FN1oCVCcvoPqRfJCZ0ZvaidFUaYIgzVDpMwLFWudDUr8+kHe6N6fIbRh9sj4mwZN8xbxIBk85GoSQUG15PA9bc2H1xA1DHttrLVTCzlt4mDxYCIS591qHNWOi2by7teRpOYzSHv1AAR5jfIIkYBcoM49WUMOFTAtK9ZSJLVXAFuqOs6yapp2HDHcJ+TjV4cOEH4aHLc8xCzH7abo9vGM9I="
  - secure: "YEMnLleD1rYClT9cSy1KAOC6caloKXWTTFXaP/h6wrsiKhfeHjgKIMAwjUxV5encYb41b2CKcth+oaQOQngYiXhRhfGEoX0D3nDJd+VAx3EfF98fS6Xromky2x02/04AsV1nRIW+cDV/sNEunaNZgV6QC6VgNuyqNSRAfiZuLr5DezRAZ3VdWjOitD3gHLlnLjwGG4tLd1Eijtab3kiXZB7DoVxoitTe+Wo4Nsf7rJOvP88eMjtA4jE0dvXhBqBQIeq6Ar/3eP0g9us64lxR2JZt5AdKAupxeKSWfeEL2clXPyFZ1uQjRPVWg0HH+aJRWCY3E0bjneidPSEBrhSEURMLuw6+q+nHFwWJlarYfWZ6WkktZH9fwXrvaaRBlZH62rdP4Is8TjJHb39JLFNJ7kCq7BlVrZg7QITIl09LFTT/hQqKpdvQY3n19xtaWbpkYoyP59jwTIyyDdM+zwsj1bgnYqqtu83BT2TBQFQNdkPBI7zqrUbT27a20ynImydu8B76vAm2aB9Yne0OfRZWdbiBrDA+TxjIUxmG4igLev84fL+VxG1jne1Kwk+/qfHQ56N+/kwCck9Fc0Jqe3d9UfXD48LyE5tPTZ6sywHAC0AGsQNKPwsj39UZF6fzHFYelzHLxVBpotCx6zPHM3VdpVvfjVHr5TDu0ERjmwsmO9g="

before_script:
  - env | sort
  - if [ "$TRAVIS_BRANCH" != "master" ] && [ -z "$TRAVIS_TAG" ]; then travis_terminate 0; fi

script:
  - if [ -n "$TRAVIS_TAG" ]; then make build-and-push; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then make update-latest; fi
